In [71]:
import pandas as pd
import numpy as np
from matplotlib import pyplot
%matplotlib
import seaborn as sns
from sklearn.model_selection import GridSearchCV

Using matplotlib backend: QtAgg


In [2]:
df=pd.read_csv(r"D:\meee'\archive (2)\diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [10]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [11]:
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [12]:
df.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [15]:
sns.heatmap(df.isnull())

<AxesSubplot:>

In [16]:
df['Pregnancies'].unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14],
      dtype=int64)

In [36]:
preg=df['Pregnancies'].value_counts().reset_index()
preg

index  Pregnancies
0       1          135
1       0          111
2       2          103
3       3           75
4       4           68
5       5           57
6       6           50
7       7           45
8       8           38
9       9           28
10     10           24
11     11           11
12     13           10
13     12            9
14     14            2
15     15            1
16     17            1

In [17]:
df['Glucose'].unique()

array([148,  85, 183,  89, 137, 116,  78, 115, 197, 125, 110, 168, 139,
       189, 166, 100, 118, 107, 103, 126,  99, 196, 119, 143, 147,  97,
       145, 117, 109, 158,  88,  92, 122, 138, 102,  90, 111, 180, 133,
       106, 171, 159, 146,  71, 105, 101, 176, 150,  73, 187,  84,  44,
       141, 114,  95, 129,  79,   0,  62, 131, 112, 113,  74,  83, 136,
        80, 123,  81, 134, 142, 144,  93, 163, 151,  96, 155,  76, 160,
       124, 162, 132, 120, 173, 170, 128, 108, 154,  57, 156, 153, 188,
       152, 104,  87,  75, 179, 130, 194, 181, 135, 184, 140, 177, 164,
        91, 165,  86, 193, 191, 161, 167,  77, 182, 157, 178,  61,  98,
       127,  82,  72, 172,  94, 175, 195,  68, 186, 198, 121,  67, 174,
       199,  56, 169, 149,  65, 190], dtype=int64)

In [37]:
glucose=df['Glucose'].value_counts().reset_index()
glucose

index  Glucose
0       99       17
1      100       17
2      111       14
3      129       14
4      125       14
..     ...      ...
131    191        1
132    177        1
133     44        1
134     62        1
135    190        1

[136 rows x 2 columns]

In [18]:
df['BloodPressure'].unique()

array([ 72,  66,  64,  40,  74,  50,   0,  70,  96,  92,  80,  60,  84,
        30,  88,  90,  94,  76,  82,  75,  58,  78,  68, 110,  56,  62,
        85,  86,  48,  44,  65, 108,  55, 122,  54,  52,  98, 104,  95,
        46, 102, 100,  61,  24,  38, 106, 114], dtype=int64)

In [38]:
BP=df['BloodPressure'].value_counts().reset_index()
BP

index  BloodPressure
0      70             57
1      74             52
2      78             45
3      68             45
4      72             44
5      64             43
6      80             40
7      76             39
8      60             37
9       0             35
10     62             34
11     66             30
12     82             30
13     88             25
14     84             23
15     90             22
16     86             21
17     58             21
18     50             13
19     56             12
20     52             11
21     54             11
22     75              8
23     92              8
24     65              7
25     85              6
26     94              6
27     48              5
28     96              4
29     44              4
30    100              3
31    106              3
32     98              3
33    110              3
34     55              2
35    108              2
36    104              2
37     46              2
38     30              2
39    122              1
40     95              1
41    102              1
42     61              1
43     24              1
44     38              1
45     40              1
46    114              1

In [19]:
df['SkinThickness'].unique()

array([35, 29,  0, 23, 32, 45, 19, 47, 38, 30, 41, 33, 26, 15, 36, 11, 31,
       37, 42, 25, 18, 24, 39, 27, 21, 34, 10, 60, 13, 20, 22, 28, 54, 40,
       51, 56, 14, 17, 50, 44, 12, 46, 16,  7, 52, 43, 48,  8, 49, 63, 99],
      dtype=int64)

In [39]:
s_thickness=df['SkinThickness'].value_counts().reset_index()
s_thickness

index  SkinThickness
0       0            227
1      32             31
2      30             27
3      27             23
4      23             22
5      33             20
6      28             20
7      18             20
8      31             19
9      19             18
10     39             18
11     29             17
12     40             16
13     25             16
14     26             16
15     22             16
16     37             16
17     41             15
18     35             15
19     36             14
20     15             14
21     17             14
22     20             13
23     24             12
24     42             11
25     13             11
26     21             10
27     46              8
28     34              8
29     12              7
30     38              7
31     11              6
32     43              6
33     16              6
34     45              6
35     14              6
36     44              5
37     10              5
38     48              4
39     47              4
40     49              3
41     50              3
42      8              2
43      7              2
44     52              2
45     54              2
46     63              1
47     60              1
48     56              1
49     51              1
50     99              1

In [21]:
df['Insulin'].unique()

array([  0,  94, 168,  88, 543, 846, 175, 230,  83,  96, 235, 146, 115,
       140, 110, 245,  54, 192, 207,  70, 240,  82,  36,  23, 300, 342,
       304, 142, 128,  38, 100,  90, 270,  71, 125, 176,  48,  64, 228,
        76, 220,  40, 152,  18, 135, 495,  37,  51,  99, 145, 225,  49,
        50,  92, 325,  63, 284, 119, 204, 155, 485,  53, 114, 105, 285,
       156,  78, 130,  55,  58, 160, 210, 318,  44, 190, 280,  87, 271,
       129, 120, 478,  56,  32, 744, 370,  45, 194, 680, 402, 258, 375,
       150,  67,  57, 116, 278, 122, 545,  75,  74, 182, 360, 215, 184,
        42, 132, 148, 180, 205,  85, 231,  29,  68,  52, 255, 171,  73,
       108,  43, 167, 249, 293,  66, 465,  89, 158,  84,  72,  59,  81,
       196, 415, 275, 165, 579, 310,  61, 474, 170, 277,  60,  14,  95,
       237, 191, 328, 250, 480, 265, 193,  79,  86, 326, 188, 106,  65,
       166, 274,  77, 126, 330, 600, 185,  25,  41, 272, 321, 144,  15,
       183,  91,  46, 440, 159, 540, 200, 335, 387,  22, 291, 39

In [40]:
insulin=df['Insulin'].value_counts().reset_index()
insulin

index  Insulin
0        0      374
1      105       11
2      130        9
3      140        9
4      120        8
..     ...      ...
181     73        1
182    171        1
183    255        1
184     52        1
185    112        1

[186 rows x 2 columns]

In [22]:
df['BMI'].unique()

array([33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31. , 35.3, 30.5,  0. , 37.6,
       38. , 27.1, 30.1, 25.8, 30. , 45.8, 29.6, 43.3, 34.6, 39.3, 35.4,
       39.8, 29. , 36.6, 31.1, 39.4, 23.2, 22.2, 34.1, 36. , 31.6, 24.8,
       19.9, 27.6, 24. , 33.2, 32.9, 38.2, 37.1, 34. , 40.2, 22.7, 45.4,
       27.4, 42. , 29.7, 28. , 39.1, 19.4, 24.2, 24.4, 33.7, 34.7, 23. ,
       37.7, 46.8, 40.5, 41.5, 25. , 25.4, 32.8, 32.5, 42.7, 19.6, 28.9,
       28.6, 43.4, 35.1, 32. , 24.7, 32.6, 43.2, 22.4, 29.3, 24.6, 48.8,
       32.4, 38.5, 26.5, 19.1, 46.7, 23.8, 33.9, 20.4, 28.7, 49.7, 39. ,
       26.1, 22.5, 39.6, 29.5, 34.3, 37.4, 33.3, 31.2, 28.2, 53.2, 34.2,
       26.8, 55. , 42.9, 34.5, 27.9, 38.3, 21.1, 33.8, 30.8, 36.9, 39.5,
       27.3, 21.9, 40.6, 47.9, 50. , 25.2, 40.9, 37.2, 44.2, 29.9, 31.9,
       28.4, 43.5, 32.7, 67.1, 45. , 34.9, 27.7, 35.9, 22.6, 33.1, 30.4,
       52.3, 24.3, 22.9, 34.8, 30.9, 40.1, 23.9, 37.5, 35.5, 42.8, 42.6,
       41.8, 35.8, 37.8, 28.8, 23.6, 35.7, 36.7, 45

In [41]:
bmi=df['BMI'].value_counts().reset_index()
bmi

index  BMI
0     32.0   13
1     31.6   12
2     31.2   12
3      0.0   11
4     32.4   10
..     ...  ...
243   36.7    1
244   41.8    1
245   42.6    1
246   42.8    1
247   46.3    1

[248 rows x 2 columns]

In [23]:
df['DiabetesPedigreeFunction'].unique()

array([0.627, 0.351, 0.672, 0.167, 2.288, 0.201, 0.248, 0.134, 0.158,
       0.232, 0.191, 0.537, 1.441, 0.398, 0.587, 0.484, 0.551, 0.254,
       0.183, 0.529, 0.704, 0.388, 0.451, 0.263, 0.205, 0.257, 0.487,
       0.245, 0.337, 0.546, 0.851, 0.267, 0.188, 0.512, 0.966, 0.42 ,
       0.665, 0.503, 1.39 , 0.271, 0.696, 0.235, 0.721, 0.294, 1.893,
       0.564, 0.586, 0.344, 0.305, 0.491, 0.526, 0.342, 0.467, 0.718,
       0.962, 1.781, 0.173, 0.304, 0.27 , 0.699, 0.258, 0.203, 0.855,
       0.845, 0.334, 0.189, 0.867, 0.411, 0.583, 0.231, 0.396, 0.14 ,
       0.391, 0.37 , 0.307, 0.102, 0.767, 0.237, 0.227, 0.698, 0.178,
       0.324, 0.153, 0.165, 0.443, 0.261, 0.277, 0.761, 0.255, 0.13 ,
       0.323, 0.356, 0.325, 1.222, 0.179, 0.262, 0.283, 0.93 , 0.801,
       0.207, 0.287, 0.336, 0.247, 0.199, 0.543, 0.192, 0.588, 0.539,
       0.22 , 0.654, 0.223, 0.759, 0.26 , 0.404, 0.186, 0.278, 0.496,
       0.452, 0.403, 0.741, 0.361, 1.114, 0.457, 0.647, 0.088, 0.597,
       0.532, 0.703,

In [42]:
dpf=df['DiabetesPedigreeFunction'].value_counts().reset_index()
dpf

index  DiabetesPedigreeFunction
0    0.258                         6
1    0.254                         6
2    0.268                         5
3    0.207                         5
4    0.261                         5
..     ...                       ...
512  1.353                         1
513  0.655                         1
514  0.092                         1
515  0.926                         1
516  0.171                         1

[517 rows x 2 columns]

In [24]:
df['Age'].unique()

array([50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 34, 57, 59, 51, 27, 41, 43,
       22, 38, 60, 28, 45, 35, 46, 56, 37, 48, 40, 25, 24, 58, 42, 44, 39,
       36, 23, 61, 69, 62, 55, 65, 47, 52, 66, 49, 63, 67, 72, 81, 64, 70,
       68], dtype=int64)

In [43]:
age=df['Age'].value_counts().reset_index()
age

index  Age
0      22   72
1      21   63
2      25   48
3      24   46
4      23   38
5      28   35
6      26   33
7      27   32
8      29   29
9      31   24
10     41   22
11     30   21
12     37   19
13     42   18
14     33   17
15     38   16
16     36   16
17     32   16
18     45   15
19     34   14
20     46   13
21     43   13
22     40   13
23     39   12
24     35   10
25     50    8
26     51    8
27     52    8
28     44    8
29     58    7
30     47    6
31     54    6
32     49    5
33     48    5
34     57    5
35     53    5
36     60    5
37     66    4
38     63    4
39     62    4
40     55    4
41     67    3
42     56    3
43     59    3
44     65    3
45     69    2
46     61    2
47     72    1
48     81    1
49     64    1
50     70    1
51     68    1

In [26]:
df['Outcome'].unique()

array([1, 0], dtype=int64)

In [44]:
outcome=df['Outcome'].value_counts().reset_index()
outcome

index  Outcome
0      0      500
1      1      268

In [46]:
X=df.drop(['Outcome'],axis='columns')
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [47]:
y=df['Outcome']

In [48]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:
len(X_train)

614

In [55]:
len(X_test)

154

In [58]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=4000)

In [59]:
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.7467532467532467

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [61]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.7467532467532467

In [62]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()

In [63]:
dtc.fit(X_train,y_train)
dtc.score(X_test,y_test)

0.7467532467532467

In [65]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import svm

In [66]:
sv = svm.SVC(C = 40, kernel = 'rbf')
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.7337662337662337

In [67]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)
gnb.score(X_test,y_test)

0.7662337662337663

In [68]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
mnb.score(X_test,y_test)

0.6623376623376623

In [69]:
model_params = {
    'svm' : {
        'model' : svm.SVC(gamma = 'auto'),
             'params' : {
                 'C' : [1,10, 20, 30, 40],
                 'kernel' : ['rbf', 'linear', 'sigmoid']
             }
        }, 
     'random_forest' : {
         'model' : RandomForestClassifier(),
         'params': {
             'n_estimators' : [1,100,500,1000]
         }
     }, 
    'gaussian_nb' : { 
        'model' : GaussianNB(), 
        'params' : {} 
        
    },
    'multinomial_nb': {
        'model' : MultinomialNB(),
        'params' : {}
        
},
    
    'decision_tree_classifier' : {
        'model' : DecisionTreeClassifier(),
        'params' : {}
    }
}

In [72]:
score = []

for model_name, mp, in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv = 5, return_train_score = False)
    clf.fit(X_train, y_train)
    score.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_
    })
    
df2 = pd.DataFrame(score, columns=['model', 'best_score', 'best_params'])
df2 

model  best_score                   best_params
0                       svm    0.765494  {'C': 1, 'kernel': 'linear'}
1             random_forest    0.775237         {'n_estimators': 500}
2               gaussian_nb    0.752472                            {}
3            multinomial_nb    0.610889                            {}
4  decision_tree_classifier    0.731267                            {}